language: python
python:
 - "3.7"
 - "3.8"
 - "3.9"
install:
  - pip install -r requirements.txt
#Run Tests
script:
    - pytest
notifications:
  email:
    recipients:
      - vdasi@ncsu.edu